QIICR/dcmqi

- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- lib/ImageSEGConverter.cpp
- lib/ImageSEGConverter.h
and use std::string instead of const char*
> Fix some invocation crashes

- apps/seg/Testing/CMakeLists.txt
- lib/ImageSEGConverter.cpp
- lib/itkTestingComparisonImageFilter.h
- lib/itkTestingComparisonImageFilter.hxx
> Fixed missing SeriesNumber

- .travis.yml
- appveyor.yml
- circle.yml
- update cmake version used on circleci and travis
- make circleci testing output verbose
> ENH: resolve several CI issues

- CMakeExternals/DCMTK.cmake
- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- appveyor.yml
- doc/seg-example.json
- include/ImageSEGConverter.h
- include/JSONSegmentationMetaInformationHandler.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
will fail in build system since some methods are only available with commit https://github.com/michaelonken/dcmtk/commit/82e831f112fd69eb461da6e282e0754ad48458cf
ctest succeeded
> In memory objects only for segmentation converters

- doc/common-schema.json
- doc/pm-example.json
- doc/pm-schema.json
- doc/seg-example.json
- doc/seg-schema.json
validation based on http://www.jsonschemavalidator.net/
> Fixed json schemata

- apps/paramaps/itkimage2paramap.cxx
- apps/seg/itkimage2segimage.cxx
- include/ConverterBase.h
- include/ImageSEGConverter.h
- include/JSONMetaInformationHandlerBase.h
- include/JSONParametricMapMetaInformationHandler.h
- include/JSONSegmentationMetaInformationHandler.h
- include/ParaMapConverter.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONMetaInformationHandlerBase.cpp
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
addresses #38
also cleaned up code a bit
TODO: finishing implementation of paramap2itkimage and supporting in memory only as well
> itkimage2paramap in memory only implemented

- .travis.yml
- appveyor.yml
- circle.yml
- doc/CMakeLists.txt
it already detects issues with the seg and pm schemas! (but that is for a separate PR)
> ENH: add ajv validation of schemas tests

- doc/CMakeLists.txt
- doc/sr-tid1500-schema.json
- added tests for example seg, pm and sr.
- fixed typo
> BUG: fixed compiling with referenced schemata

- apps/paramaps/Testing/CMakeLists.txt
- apps/paramaps/itkimage2paramap.cxx
- apps/paramaps/paramap2itkimage.cxx
- apps/paramaps/paramap2itkimage.xml
- include/ConverterBase.h
- include/JSONParametricMapMetaInformationHandler.h
- include/ParaMapConverter.h
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
- in memory only
- json meta information is populated from DICOM parametric map
fixes #38 
fixes #20 
TODO: allow more flexibility for choosing output itk format
> Implementation for DICOM parametric map to itk converter

- .travis.yml
- apps/seg/Testing/CMakeLists.txt
- appveyor.yml
- circle.yml
> ENH: added dciodvfy test for segmentation (issue #9)

- apps/sr/tid1500writer.cxx
- therefore checking first if FindingSite is available in metadata
> ENH: FindingSite should only be populated when anatomical context is available

- CMakeLists.txt
This commit is a temporary workaround waiting the issue is fixed
in upstream Slicer.
Fixes #125
> BUG: Fix extension packaging on the Slicer factories.

- apps/seg/itkimage2segimage.cxx
- otherwise the same segmentation file will be used over and over again
> BUG: Creating new reader for each input segmentation file (issue #140)

- CMake/dcmqiTest.cmake
- CMakeLists.txt
- apps/paramaps/Testing/CMakeLists.txt
- apps/seg/Testing/CMakeLists.txt
- include/dcmqi/itkTestMain.h
See #137
<s>**DO NOT MERGE**</s>
Todo:
> BUG: slicer-extension: Run tests using SEM_LAUNCH_COMMAND.

- apps/sr/tid1500writer.cxx
> BUG: Added SeriesTime and SeriesDate to Structured Report (issue #145)

- apps/paramaps/paramap2itkimage.cxx
> ENH: add debug message

- .travis.yml
- CMake/dcmqiTest.cmake
- apps/paramaps/Testing/CMakeLists.txt
- appveyor.yml
- circle.yml
This PR will fix the remaining failing tests discussed in https://github.com/QIICR/dcmqi/issues/137
> Fix parallel execution of tests

- CONTRIBUTING.md
- README.md
Modeled after https://github.com/Radiomics/pyradiomics/blob/master/CONTRIBUTING.md
> ENH: add contribution guidelines

- apps/seg/Testing/CMakeLists.txt
- doc/examples/bmmr-example.json
- doc/examples/pm-example-float.json
- doc/examples/pm-example.json
- doc/examples/seg-example.json
- doc/examples/seg-example_multiple_segments.json
- doc/schemas/pm-schema.json
- doc/schemas/seg-schema.json
- include/dcmqi/JSONParametricMapMetaInformationHandler.h
- include/dcmqi/SegmentAttributes.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
- libsrc/SegmentAttributes.cpp
related to #146 
TODO: webapp needs to be adapted to those changes
> Renamed attributes by means of DICOM Dictionary 

- apps/paramaps/paramap2itkimage.xml
- apps/seg/Testing/CMakeLists.txt
- apps/seg/segimage2itkimage.xml
might be related to https://github.com/QIICR/QuantitativeReporting/issues/135
> BUG: adding nrrd as element instead of having it as default only

- apps/seg/itkimage2segimage.cxx
- apps/seg/itkimage2segimage.xml
- include/dirent_win.h
Also improved error reporting, made DcmDataset loading more robust
re #182
> ENH: allow passing of reference DICOMs as directory

- apps/sr/tid1500writer.cxx
for structured reports
fixes #189
> ENH: Save software version and .manufacturer information into output DICOM

- js/app.js
- seg.html
- stylesheets/style.css
- validators.html
> ENH: unified display of json across all web apps, added schema examples selector

- js/app.js
- validators.html
fixes #195 
fixes #198 
http://che85.github.io/dcmqi/
> Automatic detection of schemas and examples including resolution of references

- doc/pmContexts/pm-dce-context.json
- doc/pmContexts/pm-dwi-context.json
Somehow this error is not detected by ajv. We should report it.
Re #208
> BUG: MeasurementUnitsCode attribute should be a list

- apps/paramaps/Testing/CMakeLists.txt
- apps/paramaps/paramap2itkimage.cxx
- apps/paramaps/paramap2itkimage.xml
- apps/seg/Testing/CMakeLists.txt
- apps/sr/Testing/CMakeLists.txt
- include/dcmqi/JSONMetaInformationHandlerBase.h
- include/dcmqi/JSONParametricMapMetaInformationHandler.h
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
- also set dependencies of dciodvfy tests
- added prefix parameter for output of paramap2itkimage
fixes #9
fixes #91
> ENH: added pmap/sr dciodvfy and meta roundtrip test and added missing attributes to pmap meta output

- libsrc/ImageSEGConverter.cpp
Add referenced series item only if it is not empty.
> BUG: fix referenced instances item initialization

- apps/seg/segimage2itkimage.xml
> BUG: fixes Bad XML for segimage2itkimage (issue #230)

- CMakeExternals/DCMTK.cmake
- appveyor.yml
- libsrc/ParaMapConverter.cpp
This fix needs to be merged once we are using the most recent dcmtk version mentioned in #233
> BUG: fixed typo that has been corrected in most recent dcmtk

- docker/Makefile
The package created by cpack has a different name than expected by Makefile
cc: @jcfr
> BUG: fix linux packaging issues

- docker/Makefile
> BUG: run npm with sudo to fix the issue on CircleCI

- apps/paramaps/itkimage2paramap.cxx
- apps/paramaps/paramap2itkimage.cxx
- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- apps/sr/tid1500reader.cxx
- apps/sr/tid1500writer.cxx
- apps/sr/tid1500writer.xml
- include/dcmqi/Helper.h
- libsrc/Helper.cpp
* cerr upon missing file/directory and EXIT_FAILURE
fixes #225
> ENH: adding checks for existence of file/files in file list (issue #225)

- apps/sr/tid1500reader.cxx
Thanks to Jörg Riesmeier for the hint!
> ENH: use concept code constants

- home.html
see http://che85.github.io/dcmqi
> BUG: fixing paragraphs that were displayed in columns instead of rows

- bower_components/github-fork-ribbon-css/.bower.json
- bower_components/github-fork-ribbon-css/LICENSE
- bower_components/github-fork-ribbon-css/README.md
- bower_components/github-fork-ribbon-css/bower.json
- bower_components/github-fork-ribbon-css/gh-fork-ribbon.css
- bower_components/github-fork-ribbon-css/gh-fork-ribbon.ie.css
- bower_components/github-fork-ribbon-css/index.html
- bower_components/github-fork-ribbon-css/package.json
- index.html
- stylesheets/style.css
see http://che85.github.io/dcmqi
> ENH: added "Fork me on Github" ribbon

- CMakeExternals/DCMTK.cmake
- libsrc/CMakeLists.txt
* added includes in CMakeLists.txt for allowing CLion to resolve
references
> ENH: updated dcmtk revision, included header files in the cmake library sources

- LICENSE.txt
> ENH: switch to 3-clause BSD license

- CMakeExternals/DCMTK.cmake
- apps/sr/tid1500reader.cxx
fixes partially #280 
fixes workaround introduced int #261
> ENH: updated dcmtk version

- CMakeExternals/DCMTK.cmake
- apps/sr/tid1500reader.cxx
- apps/sr/tid1500writer.cxx
- appveyor.yml
- doc/examples/sr-tid1500-ct-liver-example.json
- doc/schemas/sr-tid1500-schema.json
- include/dcmqi/TID1500Reader.h
- libsrc/CMakeLists.txt
- libsrc/TID1500Reader.cpp
This is not expected to pass the tests - will need an updated DCMTK.
> Add modifiers and parameters

- libsrc/ImageSEGConverter.cpp
> BUG: fix missing anatomic region modifier on read

- apps/sr/tid1500writer.cxx
- libsrc/TID1500Reader.cpp
@jriesmeier these should address the issues you pointed out in #305 and #309. Thank you for the review!
> STYLE: simplify code by better utilizing dcmsr capabilities

- .travis.yml
- apps/sr/Testing/CMakeLists.txt
- apps/sr/tid1500reader.cxx
- apps/sr/tid1500writer.cxx
- doc/schemas/sr-tid1500-schema.json
- include/dcmqi/TID1500Reader.h
- libsrc/TID1500Reader.cpp
Before this commit, Procedure Reported was always set to "Imaging procedure".
Related to #30
> WIP: allow to specify Procedure Reported code

- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-example.json
- doc/schemas/sr-tid1500-schema.json
- libsrc/TID1500Reader.cpp
- util/comparejson.py
re #328 
This PR is incomplete and is not ready for review or merge
> add support of algorithm identification

- apps/sr/Testing/CMakeLists.txt
- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-example-nan.json
Not completed - need to investigate why this test is failing!
```
24: Test command: /Users/fedorov/local/builds/dcmqi-updated/dcmqi-build/bin/tid1500writer "--inputMetadata" "/Users/fedorov/github/dcmqi/doc/examples/sr-tid1500-example-nan.json" "--inputImageLibraryDirectory" "/Users/fedorov/github/dcmqi/data/segmentations/ct-3slice" "--inputCompositeContextDirectory" "/Users/fedorov/github/dcmqi/data/sr-example" "--outputDICOM" "/Users/fedorov/local/builds/dcmqi-updated/dcmqi-build/Testing/Temporary/tid1500/sr-tid1500-example-nan.dcm"
24: Test timeout computed to be: 1500
24: dcmqi repository URL: https://github.com/QIICR/dcmqi.git revision: e2bd521 tag: latest-77-ge2bd521
24: Loading /Users/fedorov/github/dcmqi/data/segmentations/ct-3slice/01.dcm
24: Loading …
```
> WIP: Skip invalid measurements

- doc/examples/seg-example.json
- doc/schemas/common-schema.json
- doc/schemas/seg-schema.json
- include/dcmqi/SegmentAttributes.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
- libsrc/SegmentAttributes.cpp
> Add support of segment tracking ID/UID

- .circleci/config.yml
- .travis.yml
- apps/sr/tid1500writer.cxx
- appveyor.yml
- doc/examples/sr-tid1500-ct-liver-example.json
- doc/examples/sr-tid1500-example.json
- doc/schemas/sr-common-schema.json
- doc/schemas/sr-tid1500-schema.json
- include/dcmqi/TID1500Reader.h
- libsrc/TID1500Reader.cpp
> Improve algorithm identification support

- doc/examples/pm-example-float.json
- doc/examples/pm-example.json
- doc/examples/pm-example_no_modifier.json
- doc/schemas/common-schema.json
- doc/schemas/pm-schema.json
- include/dcmqi/JSONParametricMapMetaInformationHandler.h
- jsoncpp/json/json-forwards.h
- jsoncpp/json/json.h
- jsoncpp/jsoncpp.cpp
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
If successful, this will be a step towards replacing the custom fork of dcmqi
in MITK with the upstream
> ENH: update to jsoncpp 1.8.4

- CMakeLists.txt
Co-authored-by: Andrey Fedorov <andrey.fedorov@gmail.com>
> COMP: Ensure dcmqi can be build with DCMQI_BUILD_APPS set to OFF

- .circleci/config.yml
Co-authored-by: Andrey Fedorov <andrey.fedorov@gmail.com>
> circleci: Use workflow to separately upload latest and tagged releases

- CMake/DCMQIConfig.cmake.in
- CMakeLists.txt
Co-authored-by: Nolden Marco <M.Nolden@dkfz-heidelberg.de>
> COMP: Fix building of project against DCMQI when DCMQI_BUILD_APPS is OFF

- apps/seg/segimage2itkimage.cxx
- libsrc/ImageSEGConverter.cpp
Catch exceptions, make error messages more descriptive.
Fixes #379
> ENH: improve error reporting for seg converter

- apps/paramaps/itkimage2paramap.cxx
- apps/paramaps/paramap2itkimage.cxx
- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
- libsrc/ParaMapConverter.cpp
- catch exceptions in SEG and PM converters
- add error messages
> ENH: improve error handling

- doc/segContexts/SegmentationCategoryTypeModifier-SlicerGeneralAnatomy.json
- doc/segContexts/resources/add_slicer_ids.py
> BUG: fix and add missing codes to the Slicer terminology file

- CMakeExternals/DCMTK.cmake
- apps/paramaps/itkimage2paramap.cxx
- apps/seg/itkimage2segimage.cxx
- appveyor.yml
- doc/examples/sr-tid1500-ct-liver-example.json
- include/dcmqi/TID1500Reader.h
- libsrc/TID1500Reader.cpp
> ENH: update to DCMTK 3.6.5

- apps/seg/itkimage2segimage.cxx
- doc/examples/README.md
- doc/examples/seg-example_multiple_segments.json
- doc/examples/seg-example_multiple_segments_single_input_file.json
- doc/schemas/common-schema.json
- doc/schemas/pm-context-schema.json
- doc/schemas/pm-schema.json
- doc/schemas/seg-schema.json
- doc/schemas/segment-context-common-schema.json
- doc/schemas/sr-common-schema.json
- doc/schemas/sr-tid1500-schema.json
> ENH: add cardinality constraint to the schemas

- libsrc/ImageSEGConverter.cpp
> ENH: initialize SegmentsOverlap for simple case

- include/dcmqi/ImageSEGConverter.h
- libsrc/ImageSEGConverter.cpp
for this overload the json meta generation is optional
> #421 added overload taking a seg object

- include/dcmqi/ConverterBase.h
> BUG: PixelSpacing order incorrect on read

- CMakeExternals/DCMTK.cmake
- appveyor.yml
See https://github.com/QIICR/dcmqi/issues/341#issuecomment-778253753
> ENH: update DCMTK to 3.6.6 patched for seg

- .circleci/config.yml
- libsrc/ImageSEGConverter.cpp
Aims to address https://github.com/QIICR/dcmqi/issues/275#issuecomment-987196151
> ENH: switch from ceil() to round() for slice number calculation

- .circleci/config.yml
> CI: migrate to Ubuntu 20.04

- apps/seg/itkimage2segimage.cxx
- apps/seg/itkimage2segimage.xml
- include/dcmqi/Itk2DicomConverter.h
- libsrc/Itk2DicomConverter.cpp
> support source image references in the shared FG

- libsrc/Itk2DicomConverter.cpp
> BUG: explicitly convert to OFVector

- include/dcmqi/ConverterBase.h
- libsrc/Itk2DicomConverter.cpp
Resolves #471. Also remove printing out of the mapped instances.
> ENH: improve error messages when input is empty
