QIICR/dcmqi

- appveyor.yml
- doc/seg-example.json
- lib/ImageSEGConverter.cpp
- lib/ImageSEGConverter.h
- lib/JSONMetaInformationHandler.cpp
- lists of image instances from the input DICOM file list that match origin
of the segmentation slice are maintained
- instances that are not matchin are skipped
fixes #47 (at least, for the BMMR use case)
> ENH: add support for multiple source instances per seg frame

- doc/seg-schema.json
- lib/Exceptions.h
- lib/ImageSEGConverter.cpp
- lib/ImageSEGConverter.h
- lib/JSONMetaInformationHandler.cpp
- lib/JSONMetaInformationHandler.h
- parameterize attributes in the schema
- add access to metaInfoRoot directly in the JSON class - that class will need to be revisited
- move CHECK_COND out of the class into a macro (otherwise it is not helpful, as its main purpose is to help with the speicific location of the exception)
> BUG: remove explicit mentions of 'Iowa' and more

- doc/seg-example.json
- doc/seg-schema.json
- include/JSONSegmentationMetaInformationHandler.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
> Add handling of multiple labels per input image file

- .travis.yml
- CMakeLists.txt
- appveyor.yml
- circle.yml
- doc/CMakeLists.txt
All json files will be tested with jsonlint. npm install of jsonlint added to
all CI platforms configs. Related to #27, but just basic JSON validity checks.
> add jsonlint testing

- doc/CMakeLists.txt
The motivation is that we will have multiple tests for each object type. When a
new test is added, its name would just need to be added to the corresponding group.
> ENH: reorganize the tests into groups by object type

- apps/sr/Testing/CMakeLists.txt
- apps/sr/tid1500writer.cxx
- doc/CMakeLists.txt
- doc/sr-tid1500-ct-liver-example.json
This example encodes all measurements done by Slicer LabelStatistics, except
voxel count.
> ENH: add more common tid1500 example

- apps/sr/tid1500writer.cxx
- doc/bmmr-example.json
- doc/common-schema.json
- doc/pm-schema.json
- doc/seg-example.json
- doc/seg-schema.json
- doc/sr-common-schema.json
- doc/sr-tid1500-ct-liver-example.json
- doc/sr-tid1500-example.json
- doc/sr-tid1500-schema.json
fixes #98 
- prohibiting  additional properties
- needed to define @schema which is usually not used in json data files
- removed MeasurementGroup keyword since this name is used within definitions. Measurements already defines an array of objects which hold those values.
- corrected some typos regarding CodeSequences
- using number instead of string for measurement values how it was defined in the schema
> BUG: fixed issues with json validation (issue #98):

- apps/seg/Testing/CMakeLists.txt
- include/JSONSegmentationMetaInformationHandler.h
- libsrc/ImageSEGConverter.cpp
- libsrc/JSONMetaInformationHandlerBase.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
- util/comparejson.py
- util/jsoncompare.py
Followup on #97.
jsoncompare is from https://github.com/ChannelIQ/jsoncompare, with ChannelIQ/jsoncompare#8 applied.
> Roundtrip test and some fixes to inconsistencies between the schema, examples, and JSONMetadataHandler

- CMakeLists.txt
- SuperBuild.cmake
- apps/paramaps/CMakeLists.txt
- apps/seg/CMakeLists.txt
- apps/sr/CMakeLists.txt
- appveyor.yml
- doc/CMakeLists.txt
Per our discussion, this topic adds option `BUILD_APPS`
It also:
* ensure that the `BUILD_PARAMETRIC_MAPS` is passed to the inner build
* add `SlicerExecutionModel` as a dependency only if `BUILD_APPS` is `ON`
> Add support for build apps option

- CMakeLists.txt
- apps/CMakeLists.txt
- apps/paramaps/CMakeLists.txt
- include/dcmqi/ParaMapConverter.h
- libsrc/CMakeLists.txt
Fix consistency of the cmake flag, update paramap CLI macro parameters, make
parametric maps enabled by default.
It will make sense to remove parametric map flag completely. The reason we had
it because that component of dcmqi was being developed while parametric map API
was not yet integrated into DCMTK. Now that it is part of the stable DCMTK API,
there is no real need to make parametric map optional.
> BUG: enable parametric maps component

- Dockerfile
- docker_entry.sh
This PR adds Dockerfile to the repository (based on https://hub.docker.com/r/thewtex/centos-build/, but using the latest CMake). Since docker image can only have one entry point, the individual command line tools of dcmqi are exposed using a "selector" bash script. Note that `cmake install` does not seem to function as expected (unresolved symbols error while running from the installed location), thus executables are being run from the build tree.
> Add integration with docker

- apps/paramaps/itkimage2paramap.xml
- apps/paramaps/paramap2itkimage.cxx
- apps/paramaps/paramap2itkimage.xml
- apps/seg/itkimage2segimage.cxx
- apps/seg/itkimage2segimage.xml
- apps/seg/segimage2itkimage.cxx
- apps/seg/segimage2itkimage.xml
- apps/sr/tid1500reader.xml
- apps/sr/tid1500writer.xml
- include/dcmqi/Helper.h
- include/dcmqi/ImageSEGConverter.h
- libsrc/Helper.cpp
- libsrc/ImageSEGConverter.cpp
supported itk output formats: mhd|mha|nii|nifti|hdr|img
fixes #175
related to https://github.com/QIICR/dcmqi/pull/123
@fedorov let me know if I should add other file formats
> Support of most popular itk file formats for conversion output from dcm to itk

- include/dcmqi/ConverterBase.h
as discussed in the comment in ConverterBase.h, this warning is irrelevant and misleading,
since spacing between frames is not calculated on a per-segment basis. Spacing
is not expected to be consistent, even for individual segments, since segments can
have gaps.
> STYLE: remove warning about inconsistent frame spacing

- README.md
- apps/paramaps/Testing/CMakeLists.txt
- apps/paramaps/itkimage2paramap.xml
- apps/paramaps/paramap2itkimage.xml
- apps/seg/Testing/CMakeLists.txt
- apps/seg/itkimage2segimage.cxx
- apps/seg/itkimage2segimage.xml
- apps/seg/segimage2itkimage.xml
- apps/sr/Testing/CMakeLists.txt
- apps/sr/tid1500reader.xml
- apps/sr/tid1500writer.xml
* removed some invalid legacy descriptions
* refined some definitions
* redefined some of the arguments that are mandatory as positional arguments
(no flags)
The idea is that we should be able to include output of -h for each of these commands
directly into the documentation to make maintenance and ensuring consistency
of the documentation more manageable.
This is WIP - tests are expected to fail, and the changes will need to propagate to Slicer.
@che85 @pieper what do you think about how command line arguments are organized and named right now? Is it worth the effort changing those from how it used to be?
TODO:
> WIP: clean up CLI XML

- apps/paramaps/Testing/CMakeLists.txt
- apps/paramaps/itkimage2paramap.cxx
- apps/paramaps/itkimage2paramap.xml
- apps/paramaps/paramap2itkimage.cxx
- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- doc/examples/pm-example-float.json
- doc/examples/pm-example.json
- doc/schemas/pm-schema.json
- include/dcmqi/ConverterBase.h
- include/dcmqi/ImageSEGConverter.h
- include/dcmqi/ParaMapConverter.h
- libsrc/ImageSEGConverter.cpp
- libsrc/ParaMapConverter.cpp
work towards addressing #186 
At the moment, crashes `itkimage2paramap_makeParametricMap` test
Stack trace:
```
#0  0x00007fff86043286 in __pthread_kill ()
#1  0x00007fff860189f9 in pthread_kill ()
#2  0x00007fff8a93d9a3 in abort ()
#3  0x00007fff834271cb in free ()
#4  0x0000000102687cd9 in IODComponent::~IODComponent (this=0x7fff5fbf51f8) at /Users/fedorov/local/builds/dcmqi-new-super/DCMTK/dcmiod/libsrc/modbase.cc:65
#5  0x000000010266612b in DcmIODUtil::freeContainer<OFVector<IODSeriesAndInstanceReferenceMacro::ReferencedSeriesItem*> > (container=@0x7fff5fbf8200) at iodutil.h:840
#6  0x000000010268afa7 in IODCommonInstanceReferenceModule::freeMemory (this=0x7fff5fbf81e0) at /Users/fedorov/local/builds/dcmqi-new-super/DCMTK/dcmiod/libsrc/modcommoninstanceref.cc:353
#7 …
```
> Add derivation images to parametric map

- circle.yml
- docker/Makefile
Since the current tag are neither annotated or signed, this commit
updates the logic to be able to resolve lightweight tags.
Lightweight tags are just pointer to a specific commit and are not
associated with "Tagger" information.
See https://git-scm.com/book/en/v2/Git-Basics-Tagging
> circle: Fix discovery of git tag associated with docker image generation

- CMake/FindGit.cmake
- CMake/dcmqiVersionConfigure.h.in
- apps/paramaps/itkimage2paramap.cxx
- apps/paramaps/paramap2itkimage.cxx
- apps/seg/itkimage2segimage.cxx
- apps/seg/segimage2itkimage.cxx
- apps/sr/tid1500reader.cxx
- apps/sr/tid1500writer.cxx
With the current setup, especially with the use of Docker images, it is not easy
to determine the version of the software being used. This commit adds console
output of the git hash and tag (when available) as the first line in the command
line output of the converters.
> ENH: add version reporting to the converters output

- doc/examples/pm-example-float.json
- doc/examples/pm-example.json
- doc/pmContexts/pm-dce-context.json
- doc/pmContexts/pm-dwi-context.json
- doc/schemas/pm-context-schema.json
- doc/schemas/pm-schema.json
- libsrc/ParaMapConverter.cpp
As discussed with David Clunie, "QUANTITY" will be proposed to be used for all
Parametric maps. Note that this relies on a CP that has not even been submitted
yet! Resolves #216.
> ENH: remove DerivedPixelContrast initialization

- apps/paramaps/itkimage2paramap.xml
- apps/paramaps/paramap2itkimage.xml
- apps/seg/itkimage2segimage.xml
- apps/seg/segimage2itkimage.xml
This fixes CLI type from file to directory where appropriate, assigns label to
parameter names, and separates advanced options.
This is important when using converters from Slicer UI, which may be easier than
dealing with the issues of path separators and other Windows idiosyncrasies while
running converters from the command line.
> BUG: fix several issues with CLI XML

- libsrc/ImageSEGConverter.cpp
Abort conversion if the number of inner lists does not match the number of input
segmentations.
Fixes #243
> BUG: check for the number of inner lists in metadata

- libsrc/ParaMapConverter.cpp
Add referenced series item only if it is not empty.
This fix was missed while patching the same bug in the SEG converter in #227
> BUG: fix referenced instances item initialization

- apps/sr/tid1500reader.cxx
- doc/schemas/sr-tid1500-schema.json
- TrackingUniqueIdentier, activitySession, timePoint
- fix capitalization of activitySession and timePoint to be consistent with
the schema, and the conventions, since these are not DICOM tags, but concept
code mapped
> ENH: add output of missing SR TID1500 attributes

- apps/sr/tid1500reader.cxx
Before this fix, the whole tree was searched while looking for the derivation concept
child node. Fixes #261.
> BUG: fix initialization of the derivation

- libsrc/ImageSEGConverter.cpp
- libsrc/ParaMapConverter.cpp
Due to a fixed bug in DCMTK - see discussion in
https://github.com/QIICR/QuantitativeReporting/issues/170#issuecomment-317540337
the order of parameters passed to import changed and dcmqi was incorrectly
importing series attributes, and not importing frame of reference.
> BUG: fix the order of parameters to import() call

- .travis.yml
- appveyor.yml
- circle.yml
See #260
```
$ git shortlog 0.17.0..0.18.0 --no-merges
Jean-Christophe Fillion-Robin (1):
publish_github_release: Update githubrelease 1.5.6 to handle leftover tmp release tag
```
This commit fixes exception like the following happening when the temporary
release tag (e.g latest-tmp) remains for a previous failed attempt to upload
packages.
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/anyci/publish_github_release.py", line 443, in <module>
main()
File "/usr/local/lib/python2.7/site-packages/anyci/publish_github_release.py", line 436, in main
_upload_prerelease(args)
File "/usr/local/lib/python2.7/site-packages/anyci/publish_github_release.py", line 346, in _upload_prerelease
target_commitish=sha
File …
```
> ci: Update scikit-ci-addons to handle leftover temporary release tag

- libsrc/TID1500Reader.cpp
This was missed while updating the code in #287. Testing didn't catch this,
because TrackingUniqueIdentifier is generated by the converter, and is not
supplied in the input JSON.
> BUG: read TrackingUniqueIdentifier

- CMakeLists.txt
With update of the minimum required version of CMake to 3.5.0 in Slicer,
default value for CMAKE_MACOSX_RPATH changed to ON but Slicer required this
option to be OFF.
This commit makes sure the value passed by the Slicer extension build
system is used consistently.
This commit associated with the use of Slicer >= r26305 [1]
will prevent error like the following:
```
Error copying file "@rpath/libitkminc2-4.12.1.dylib" to "/.../DCMQI-build/dcmqi-build/_CPack_Packages/Darwin/TGZ/26304-macosx-amd64-DCMQI-git87fce09-2017-08-23/Slicer.app/Contents/lib/Slicer-4.7/libitkminc2-4.12.1.dylib".
```
Related Slicer discussions:
https://discourse.slicer.org/t/interpreting-cdash-reporting-extension-is-packaged-despite-build-errors/856
https://discourse.slicer.org/t/extension-build-failure-on-mac-due-to-e …
> COMP: Consistently propagate CMAKE_MACOSX_RPATH to all projects

- SuperBuild.cmake
This commit ensures the step attempts to remove an existing file by
fixing a regression introduced in b569199 (cmake: Introduce PROJECT_NAME_LC
var to allow consistent naming of inner build dir)
> cmake: Fix forcebuild step

- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-ct-liver-example.json
- doc/schemas/sr-tid1500-schema.json
- libsrc/TID1500Reader.cpp
This aims to address #305. Schema extended to support numeric and text properties
of the measurement, as suggested by @dclunie in
https://github.com/QIICR/dcmqi/issues/305#issuecomment-335172718
Since these attributes are not supported by the dcmsr wrapper class, they are added
in a separate iteration by iterating over all measurement items using gotoAnnotatedNode(),
and setting measurement properties, when applicable.
Reading SR and saving JSON is not supported yet.
> WIP: add support for initializing measurement properties

- apps/paramaps/Testing/CMakeLists.txt
- doc/examples/pm-example_no_modifier.json
- libsrc/JSONParametricMapMetaInformationHandler.cpp
- libsrc/JSONSegmentationMetaInformationHandler.cpp
fixes #320 
* instead of reading values directly, making sure that the attributes
exist before attempting to access them
> BUG: read unavailable JSON::Value attribute initializes it to NULL

- libsrc/Helper.cpp
Philips datasets can contain RawDataStorage instances within MR series, which caused
problems in the dataset from @curtislisle. This commit makes sure that every derivation
dataset contains PixelData. Thanks to @JoostJM for the background and the idea!
Related to #322
> ENH: check that source file contains PixelData

- .gitignore
- util/measurementReportUtils/__init__.py
- util/measurementReportUtils/codeSequences.py
- util/measurementReportUtils/findings.py
- util/measurementReportUtils/measurementGroup.py
- util/measurementReportUtils/measurementItem.py
- util/measurementReportUtils/measurementReport.py
These are a few classes I used to be able to conveniently put together measurement reports from custom data storage in a python batch processing script. The classes allow export to JSON which then can directly be processed by the tid1500 writer.
Currently these classes are still quite specific to my task (converting Prostate MRI Test-Retest Data/Measurements to DICOM). However I think the basic idea is nice and can be easily extended to be much more generic. The classes are mainly data structures with the same layout as the respective parts of the JSON meta file, plus some convenience methods (e.g. exporting as JSON, adding sub-items).
To make it more generic my idea would be to extend e.g. the Findings and MeasurementItem classes by proper factories that create all the typical objects by …
> Util Classes to build Measurement Report and generate JSON

- libsrc/JSONSegmentationMetaInformationHandler.cpp
- ClinicalTrialSeriesID has always been set to `Session1` for all
generated segmentations
> BUG: ClinicalTrialSeriesID was never read properly from metadata

- docker/Makefile
When the container is created, it does not have the name
'dockcross/manylinux-x64'. This is the name of the image as opposed to
the container. Docker gives a random, human-readable name
to a container if the `--name` flag is not provided.
Use the `--rm` flag so the container does not need to be removed.
> BUG: Fix dockcross script creation container cleanup

- include/dcmqi/ConverterBase.h
- libsrc/ImageSEGConverter.cpp
- do not print out ITK image, directions, matrices - not helpful
- do print out how many segmentation slices were mapped to the source DICOM images
TODO:
> clean up console output

- .circleci/config.yml
- apps/sr/Testing/CMakeLists.txt
- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-qualitative.json
- doc/schemas/sr-tid1500-schema.json
- libsrc/TID1500Reader.cpp
Aims to address #352.
Unresolved issue that needs to be discussed is summarized below in an email sent to @dclunie today:
>Today I was working on adding support for qualitative evaluations to dcmqi, and it occurred to me that it would 1) be more consistent and 2) simplify implementation, if the qualitative assessment items (rows 16 and 17) in TID 1411 [1] were nested within a container with the heading (C0034375, UMLS, "Qualitative Evaluations"), as it is done in TID 1500 row 12 [2].
>
> As is right now, I think it is confusing since there are other CODE items in 1411 (e.g., "Finding"), and the order of items is non-significant. So I guess to parse the document, one would need to look for all CODEs that do not have concepts that otherwise can appear in the document per template structure. …
> WIP: Add qualitative evaluations to TID 1500 converters

- .circleci/config.yml
Since GITHUB_TOKEN is usually not available when building PR, this commit
prevents failure.
See https://github.com/QIICR/dcmqi/pull/351#issuecomment-415489912
> circleci/publish_github_release: do not fail if there no token available

- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-example.json
- doc/schemas/sr-tid1500-schema.json
- libsrc/TID1500Reader.cpp
Note Laterality is located at the same level as Finding Site in
the input JSON, not subordinate to Finding Site.
Fixes #358
> ENH: add support for finding site laterality

- apps/sr/tid1500reader.cxx
- apps/sr/tid1500writer.cxx
- doc/examples/sr-tid1500-ct-liver-example.json
- doc/schemas/sr-common-schema.json
- include/dcmqi/TID1500Reader.h
- libsrc/TID1500Reader.cpp
This functionality was needed in particular to be able to better describe software version in https://github.com/Radiomics/pyradiomics/pull/437.
> ENH: add support for describing device observer context

- .circleci/config.yml
This commit fixes a regression introduced in 529dccd5 (circleci: Use
workflow to separately upload latest and tagged releases). It creates
a virtual environment to avoid error like the following:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/lxml'
> ci: Fix installation of python packages in deploy-* jobs

- .circleci/config.yml
This commit fixes the following error:
RuntimeError: Current directory is expected to be inside a git working tree: /home/circleci/project
> ci: Add missing checkout comment to CircleCI deploy-* jobs

- appveyor.yml
- docker/Makefile
- include/dcmqi/ConverterBase.h
Based on the observed very tiny invalid values for SpacingBetweenSlices
in the SEGs generated by TeraRecon.
> ENH: compare to epsilon instead of zero

- include/dcmqi/ConverterBase.h
When a single frame was loaded, sliceExtent was left uninitialized (instead of set to 0.0), which prevented computation of number of frames.
Fixes loading of file mentioned in https://discourse.slicer.org/t/loading-dicom-segmentation/14139/4
> BUG: Fix loading of single-frame segmentation

- apps/seg/itkimage2segimage.cxx
- apps/seg/itkimage2segimage.xml
- apps/seg/segimage2itkimage.cxx
- apps/seg/segimage2itkimage.xml
- libsrc/ImageSEGConverter.cpp
I had really hard time figuring out why segmentation export fails, and it turned out that the in the input DICOM images ProcedureCodeSequence was defined but did not contain any items, and because of this DCMTK refused to create the segmentation object. It took several hours of debugging to investigate this issue.
Along the way, I realized that DCMTK provides pretty detailed logging of all relevant details, but this logging is not enabled. To prevent such tedious investigations in the future, I added a --verbose command-line switch to segmentation converters, which enable printing of detailed information. It prints debug-level messages, which can be quite detailed, so by default the switch is disabled.
> ENH: Added detailed logging option to itkimage2segimage and segimage2itkimage

- Design/DICOMSegmentationConverter.puml
- include/dcmqi/Helper.h
- libsrc/Helper.cpp
- libsrc/ImageSEGConverter.cpp
- libsrc/ParaMapConverter.cpp
API-breaking change: Helper::floatToStrScientific() was renamed to
Helper::floatToStr().
Signed-off-by: Stefan Dinkelacker <s.dinkelacker@dkfz-heidelberg.de>
> BUG: serialize floats with maximum precision

- include/dcmqi/ConverterBase.h
- libsrc/ImageSEGConverter.cpp
re #449
It was assumed that in case of multiple input segmentation files, all
of them had the same geometry.
> BUG: fix initialization of referenced instances

- libsrc/CMakeLists.txt
DCMTK 3.6.7 introduced targets like DCMTK::dcmdata which should be used instead of the old style listing all modules and include directory
> support for new dcmtk targets

- docker/Makefile
- docker/dcmqi/Dockerfile
This commit is a follow-up of eca78a5c5 (replace deprecated dockcross image) updating the build environment from `dockcross/manylinux-x64` to `dockcross/manylinux2014-x64`.
Since `dockcross/manylinux2014-x64` is based on Centos 7, this commit also updates the base distribution associated with the dcmqi docker image to be consistent.
See https://github.com/pypa/manylinux#manylinux2014-centos-7-based
> BUG: Ensure binaries bundled into dcmqi docker image can run

- .github/workflows/cmake-win.yml
Use powershell multi-line command separators (backticks) for long command line call.
> Fix Windows Release publishing.

- .github/workflows/cmake-linux.yml
- .github/workflows/cmake-macos.yml
As already implemented for Windows, only publish packages, if dcmqi
build is not triggered by pull request (only) and also if build
happens on the qiicr/dcmqi repo.
> Only publish on master and on qiicr/dcmqi repo.

- libsrc/ImageSEGConverter.cpp
- libsrc/ParaMapConverter.cpp
Speedup writing of DICOM segmentation and parametric map objects by disabling functional group checking when writing.
> ENH: Don't check functional groups (speedup)

- .github/workflows/cmake-linux.yml
- .github/workflows/cmake-macos.yml
- .github/workflows/cmake-win.yml
To address #482, I found that the reason for scikit unable to make releases with tagged commits (w/ versioned tags). The git checkout action does not fetch tags unless we explicitly mention it. Some discussion can be seen here..https://github.com/actions/checkout/issues/206
I came to know about this issue when I simply wanted to see the tags while running the GitHub actions workflow with 'git describe' and the logs said no tags found. I then searched if this is a common issue and found the above discussion.
> Add fetch tags to exisitng workflows

- include/dcmqi/OverlapUtil.h
- include/dcmqi/framesorter.h
- libsrc/OverlapUtil.cpp
OverlapUtil:
- Use framesorter class instead of using homegrown sorting.
- Remove the related (then) unused sorting functionality
FrameSorter class: 
- Remember frame positions in Result
- Also remember frame positions in sorting result since it is usually
accessed anyway and interesting for library users that otherwise call
the underlying method on FGInterface for all frames again.
- The DummySorter does not provide frame positions to keep it as simple
as possible (i.e. keep  it "zero" cost).
- Allow 2^32-1 frames as permitted in in DICOM (i.e. use Uint32 instead
of  Uint16) for frame number index.
- Changed precision from Float32 to Float64 where applicable.
- Added some documentation and some other small changes.
> Switch to framesorter class

- libsrc/Itk2DicomConverter.cpp
The order in which the values for pixel spacing in ITK and DICOM are stored is different. In DICOM the first value is the row spacing (i.e. Y axis) while in ITK the first value is spacing along the X axis.
Reading asymmetric spacings from DICOM segmentations has already been fixed in 46c6f0.
This commit fixes writing DICOM segmentation objects with asymmetric spacings.
> Fix order of pixel spacing converting ITK->DICOM.

- doc/examples/seg-example.json
- doc/examples/seg-example_multiple_segments.json
- doc/examples/seg-example_multiple_segments_reordered.json
- doc/examples/seg-example_multiple_segments_single_input_file.json
- libsrc/Itk2DicomConverter.cpp
This will be done when SegmentLabel is not passed in configuration. SegmentDescription is better than using CodeMeaning from SegmentationType, as it allows more precise control by the user.
> ENH: use SegmentDescription to populate SegmentLabel

- .github/workflows/cmake-macos.yml
- apps/seg/segimage2itkimage.cxx
- apps/seg/segimage2itkimage.xml
I do not see a reason to restrict this feature to NRRD
> allow saving merged segments to all formats

- CMakeExternals/SlicerExecutionModel.cmake
- apps/seg/Testing/CMakeLists.txt
- apps/seg/itkimage2segimage.xml
re #498
It appears that defaults are ignored for boolean SEM parameters. Even though the parameter was set to true in https://github.com/QIICR/dcmqi/blob/2990dbd01d1fa61c16777950732ff19dc87318e3/apps/seg/itkimage2segimage.xml#L58-L65, the default reported by the executable was 0.
Local tests show that integer parameters do not have this problem.
Also switch to the most recent has for SlicerExecutionModel.
> bug: switch to integer for the skip flag

- apps/seg/itkimage2segimage.cxx
- include/dcmqi/ConverterBase.h
- include/dcmqi/Itk2DicomConverter.h
- libsrc/Itk2DicomConverter.cpp
Use constant pointers to input segmentation images (`itk::Image::ConstPointer`) since we don't expect the function to change these images.
> Use const pointer to input segmentations

- .github/workflows/cmake-linux.yml
- .github/workflows/cmake-win.yml
- CMakeLists.txt
- apps/paramaps/Testing/CMakeLists.txt
- apps/seg/Testing/CMakeLists.txt
- apps/sr/Testing/CMakeLists.txt
Use the CMake Python3 module instead of PythonInterp, which it has
replaced with the Interpreter COMPONENT.
Use Python 3 instead of Python 2, which is end-of-life.
Ensure we use ${Python3_EXECUTABLE} in the test commands.
> COMP: Update python executable location and usage
